import connectDB from '../lib/mongodb.js';
import User from '../models/User.js';

const seedUsers = async () => {
  try {
    await connectDB();
    console.log('Connected to MongoDB');

    // Clear existing users (optional - remove this in production)
    await User.deleteMany({});
    console.log('Cleared existing users');

    // Seed users
    const users = [
      // Admin user
      {
        name: "Admin Permanent",
        email: "admin@joyapps.com",
        password: "admin123",
        role: "admin",
        avatar: null,
        locked: "unlocked",
        department: "Management",
        position: "System Administrator",
        salary: 80000,
        joinDate: "2023-01-01",
        phoneNumber: "+1-555-0001",
        address: "123 Admin St, Admin City, AC 12345",
        emergencyContact: "Admin Emergency",
        emergencyPhone: "+1-555-0002",
        contactNumber: "+1-555-0001",
        emergencyNumber: "+1-555-0002",
        dateOfBirth: "1985-01-01",
        socialSecurityNumber: "000-00-0001",
        bankAccount: "****0001",
        benefits: "Full Benefits Package",
        notes: "System administrator with full access",
        assignedUsers: [],
        defaultTasker: "none",
        vacationDay: "Monday",
        employeeId: "ADM001",
        target: 0,
        attendance: 100,
        lastReview: "2024-01-01",
        performance: 100,
        links: 0
      },
      // Manager user
      {
        name: "Muhammad Shahood",
        email: "Shahood1@joyapps.net",
        password: "manager123",
        role: "manager",
        avatar: null,
        assignedUsers: [],
        locked: "unlocked",
        department: "Management",
        position: "Team Manager",
        salary: 65000,
        joinDate: "2023-02-01",
        phoneNumber: "+1-555-0101",
        address: "456 Manager Ave, Manager City, MC 23456",
        emergencyContact: "Manager Emergency",
        emergencyPhone: "+1-555-0102",
        contactNumber: "+1-555-0101",
        emergencyNumber: "+1-555-0102",
        dateOfBirth: "1988-05-15",
        socialSecurityNumber: "111-11-1111",
        bankAccount: "****1111",
        benefits: "Health, Dental, Vision",
        notes: "Experienced team manager",
        defaultTasker: "none",
        vacationDay: "Tuesday",
        employeeId: "MGR001",
        target: 0,
        attendance: 98,
        lastReview: "2024-01-15",
        performance: 95,
        links: 0
      },
      // Additional Manager user
      {
        name: "Sarah Manager",
        email: "manager@joyapps.com",
        password: "manager123",
        role: "manager",
        avatar: null,
        assignedUsers: [],
        locked: "unlocked",
        department: "Management",
        position: "Operations Manager",
        salary: 62000,
        joinDate: "2023-03-01",
        phoneNumber: "+1-555-0201",
        address: "789 Manager Blvd, Manager City, MC 34567",
        emergencyContact: "Sarah Emergency",
        emergencyPhone: "+1-555-0202",
        contactNumber: "+1-555-0201",
        emergencyNumber: "+1-555-0202",
        dateOfBirth: "1990-08-20",
        socialSecurityNumber: "222-22-2222",
        bankAccount: "****2222",
        benefits: "Health, Dental, Vision",
        notes: "Operations manager with strong leadership skills",
        defaultTasker: "none",
        vacationDay: "Wednesday",
        employeeId: "MGR002",
        target: 0,
        attendance: 97,
        lastReview: "2024-01-20",
        performance: 92,
        links: 0
      },
      // QC user
      {
        name: "John QC",
        email: "qc@joyapps.com",
        password: "qc123",
        role: "qc",
        avatar: null,
        locked: "unlocked",
        department: "Quality Control",
        position: "Quality Control Specialist",
        salary: 55000,
        joinDate: "2023-04-01",
        phoneNumber: "+1-555-0301",
        address: "321 QC Street, QC City, QC 45678",
        emergencyContact: "John Emergency",
        emergencyPhone: "+1-555-0302",
        contactNumber: "+1-555-0301",
        emergencyNumber: "+1-555-0302",
        dateOfBirth: "1987-12-10",
        socialSecurityNumber: "333-33-3333",
        bankAccount: "****3333",
        benefits: "Health, Dental",
        notes: "Detail-oriented quality control specialist",
        assignedUsers: [],
        defaultTasker: "none",
        vacationDay: "Thursday",
        employeeId: "QC001",
        target: 0,
        attendance: 99,
        lastReview: "2024-01-25",
        performance: 88,
        links: 0
      },
      // HR user
      {
        name: "Sarah HR",
        email: "hr@joyapps.com",
        password: "hr123",
        role: "hr",
        avatar: null,
        locked: "unlocked",
        department: "Human Resources",
        position: "HR Specialist",
        salary: 58000,
        joinDate: "2023-05-01",
        phoneNumber: "+1-555-0401",
        address: "654 HR Lane, HR City, HR 56789",
        emergencyContact: "Sarah HR Emergency",
        emergencyPhone: "+1-555-0402",
        contactNumber: "+1-555-0401",
        emergencyNumber: "+1-555-0402",
        dateOfBirth: "1989-03-25",
        socialSecurityNumber: "444-44-4444",
        bankAccount: "****4444",
        benefits: "Full Benefits Package",
        notes: "Experienced HR professional",
        assignedUsers: [],
        defaultTasker: "none",
        vacationDay: "Friday",
        employeeId: "HR001",
        target: 0,
        attendance: 96,
        lastReview: "2024-01-30",
        performance: 90,
        links: 0
      },
      // Regular users
      {
        name: "Hasan Abbas",
        email: "hasan@joyapps.net",
        password: "user123",
        role: "user",
        avatar: null,
        taskRole: "both",
        locked: "unlocked",
        workerType: "permanent",
        status: "permanent",
        department: "Operations",
        position: "Permanent Worker",
        salary: 45000,
        joinDate: "2023-06-01",
        phoneNumber: "+1-555-0501",
        address: "987 Worker St, Worker City, WC 67890",
        emergencyContact: "Aisha Shahood",
        emergencyPhone: "+1-555-0502",
        contactNumber: "+1-555-0501",
        emergencyNumber: "+1-555-0502",
        dateOfBirth: "1990-05-15",
        socialSecurityNumber: "555-55-5555",
        bankAccount: "****5555",
        benefits: "Health, Dental, Vision",
        notes: "Excellent performer, potential for promotion",
        assignedUsers: [],
        defaultTasker: "none",
        vacationDay: "Monday",
        employeeId: "WRK001",
        target: 50,
        attendance: 98,
        lastReview: "2024-01-15",
        performance: 92,
        links: 0
      },
      {
        name: "Adnan Amir",
        email: "adnan@joyapps.net",
        password: "user123",
        role: "user",
        avatar: null,
        taskRole: "viewer",
        locked: "unlocked",
        workerType: "permanent",
        status: "permanent",
        department: "Operations",
        position: "Permanent Worker",
        salary: 42000,
        joinDate: "2023-07-01",
        phoneNumber: "+1-555-0601",
        address: "147 Viewer Ave, Viewer City, VC 78901",
        emergencyContact: "Mike Johnson",
        emergencyPhone: "+1-555-0602",
        contactNumber: "+1-555-0601",
        emergencyNumber: "+1-555-0602",
        dateOfBirth: "1988-12-03",
        socialSecurityNumber: "666-66-6666",
        bankAccount: "****6666",
        benefits: "Health, Dental",
        notes: "Reliable team member",
        assignedUsers: [],
        defaultTasker: "none",
        vacationDay: "Tuesday",
        employeeId: "WRK002",
        target: 40,
        attendance: 95,
        lastReview: "2024-01-10",
        performance: 88,
        links: 0
      },
      {
        name: "Waleed Bin Shakeel",
        email: "waleed@joyapps.net",
        password: "user123",
        role: "user",
        avatar: null,
        workerType: "trainee",
        status: "trainee",
        taskRole: "clicker",
        locked: "unlocked",
        department: "Operations",
        position: "Trainee Worker",
        salary: 35000,
        joinDate: "2024-01-08",
        phoneNumber: "+1-555-0701",
        address: "258 Trainee Blvd, Trainee City, TC 89012",
        emergencyContact: "Fatima Abbas",
        emergencyPhone: "+1-555-0702",
        contactNumber: "+1-555-0701",
        emergencyNumber: "+1-555-0702",
        dateOfBirth: "1985-08-22",
        socialSecurityNumber: "777-77-7777",
        bankAccount: "****7777",
        benefits: "Health, Dental, Vision, 401k",
        notes: "Top performer, team lead material",
        assignedUsers: [],
        defaultTasker: "none",
        vacationDay: "Wednesday",
        employeeId: "TRN001",
        target: 30,
        attendance: 92,
        lastReview: "2024-01-25",
        performance: 78,
        links: 0
      }
    ];

    // Insert users
    const createdUsers = await User.insertMany(users);
    console.log(`Created ${createdUsers.length} users successfully`);

    // Display created users
    createdUsers.forEach(user => {
      console.log(`- ${user.name} (${user.email}) - ${user.role}`);
    });

    console.log('Database seeding completed successfully!');
    process.exit(0);

  } catch (error) {
    console.error('Error seeding database:', error);
    process.exit(1);
  }
};

// Run the seed function
seedUsers();
